from abc import ABC, abstractmethod

import httpx

from config import get_settings
from utils.constants import ALLOWED_MENTAL_HEALTH_TOPICS, SAFETY_DISCLAIMER, SELF_HARM_KEYWORDS


SYSTEM_PROMPT = """
You are Harmony AI Virtual Intelligence, a calm and empathetic wellness assistant.
You can only answer topics related to:
depression, anxiety, loneliness, stress, overthinking, motivation, sadness,
emotional pain, self doubt, fear, confidence, life balance, inner peace.

For allowed topics, your response must include:
1) Practical support
2) Emotional guidance
3) Bhagavad Gita inspired wisdom
4) The exact disclaimer:
"Generated by Harmony AI Virtual Intelligence. This guidance may contain mistakes. Please seek a qualified professional for serious concerns."

If user asks unrelated topics, politely refuse and ask them to ask a mental wellness question.
""".strip()


class ChatProvider(ABC):
    @abstractmethod
    async def generate(self, message: str) -> str:
        raise NotImplementedError


class MockProvider(ChatProvider):
    async def generate(self, message: str) -> str:
        return (
            "Practical support: Try a 5-minute reset now: drink water, take ten slow breaths, and write down one small next step.\n\n"
            "Emotional guidance: It is okay to feel heavy emotions. You are not weak for struggling, and healing can happen gradually.\n\n"
            "Bhagavad Gita inspired wisdom: In the Gita, Krishna reminds us to focus on right action in the present moment, without being consumed by fear of outcomes.\n\n"
            f"{SAFETY_DISCLAIMER}"
        )


def _looks_like_placeholder(value: str) -> bool:
    normalized = value.strip().lower()
    return (not normalized) or ("your_key_here" in normalized) or ("placeholder" in normalized)


class AzureOpenAIProvider(ChatProvider):
    async def generate(self, message: str) -> str:
        settings = get_settings()
        if _looks_like_placeholder(settings.azure_openai_api_key):
            return await MockProvider().generate(message)

        base_endpoint = settings.azure_openai_endpoint.rstrip("/")
        url = (
            f"{base_endpoint}/openai/deployments/{settings.azure_openai_deployment}/chat/completions"
            f"?api-version={settings.azure_openai_api_version}"
        )
        payload = {
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": message},
            ],
            "temperature": 0.6,
            "max_tokens": 500,
        }
        headers = {
            "Content-Type": "application/json",
            "api-key": settings.azure_openai_api_key,
        }

        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"].strip()


class OpenAIProvider(ChatProvider):
    async def generate(self, message: str) -> str:
        settings = get_settings()
        if _looks_like_placeholder(settings.openai_api_key):
            return await MockProvider().generate(message)
        url = "https://api.openai.com/v1/chat/completions"
        payload = {
            "model": "gpt-4o-mini",
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": message},
            ],
            "temperature": 0.6,
        }
        headers = {
            "Authorization": f"Bearer {settings.openai_api_key}",
            "Content-Type": "application/json",
        }

        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"].strip()


class GeminiProvider(ChatProvider):
    async def generate(self, message: str) -> str:
        settings = get_settings()
        if _looks_like_placeholder(settings.gemini_api_key):
            return await MockProvider().generate(message)

        endpoint = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            "gemini-1.5-flash:generateContent"
        )
        url = f"{endpoint}?key={settings.gemini_api_key}"
        payload = {
            "contents": [{"role": "user", "parts": [{"text": f"{SYSTEM_PROMPT}\n\nUser: {message}"}]}]
        }
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(url, json=payload, headers={"Content-Type": "application/json"})
            response.raise_for_status()
            data = response.json()
            parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
            text = "".join(part.get("text", "") for part in parts).strip()
            if text:
                return text
            return await MockProvider().generate(message)


def _has_self_harm_risk(message: str) -> bool:
    lowered = message.lower()
    return any(keyword in lowered for keyword in SELF_HARM_KEYWORDS)


def _is_allowed_topic(message: str) -> bool:
    lowered = message.lower()
    return any(topic in lowered for topic in ALLOWED_MENTAL_HEALTH_TOPICS)


def _get_provider() -> ChatProvider:
    provider = get_settings().chat_provider
    if provider == "azure_openai":
        return AzureOpenAIProvider()
    if provider == "openai":
        return OpenAIProvider()
    if provider == "gemini":
        return GeminiProvider()
    return MockProvider()


async def generate_chat_response(message: str) -> tuple[str, str]:
    if _has_self_harm_risk(message):
        emergency = (
            "I am really glad you reached out. You matter, and you deserve immediate support.\n\n"
            "Practical support: If you are in immediate danger, call your local emergency number now. "
            "If possible, stay with someone you trust and remove anything that could harm you.\n\n"
            "Emotional guidance: You do not have to carry this pain alone. Reaching out right now is a strong and brave step.\n\n"
            "Bhagavad Gita inspired wisdom: Even in moments of deep darkness, the Gita teaches that your inner self has enduring strength, and help is a form of courage.\n\n"
            f"{SAFETY_DISCLAIMER}"
        )
        return emergency, "safety"

    if not _is_allowed_topic(message):
        refusal = (
            "I can help only with mental wellness topics such as anxiety, stress, loneliness, motivation, sadness, confidence, and inner peace.\n\n"
            "Please ask me a question in one of these areas.\n\n"
            f"{SAFETY_DISCLAIMER}"
        )
        return refusal, "restricted"

    provider = _get_provider()
    content = await provider.generate(message)
    if SAFETY_DISCLAIMER not in content:
        content = f"{content}\n\n{SAFETY_DISCLAIMER}"
    return content, get_settings().chat_provider
