ALLOWED_MENTAL_HEALTH_TOPICS = {
    "depression",
    "anxiety",
    "loneliness",
    "stress",
    "overthinking",
    "motivation",
    "sadness",
    "emotional pain",
    "self doubt",
    "fear",
    "confidence",
    "life balance",
    "inner peace",
}

SELF_HARM_KEYWORDS = {
    "suicide",
    "kill myself",
    "end my life",
    "self harm",
    "hurt myself",
    "die",
    "can't go on",
}

SAFETY_DISCLAIMER = (
    "Generated by Harmony AI Virtual Intelligence. This guidance may contain mistakes. "
    "Please seek a qualified professional for serious concerns."
)

SKIN_LABEL_CONTEXT = {
    "eczema": {
        "description": "Eczema can cause dry, itchy, and inflamed skin patches.",
        "recommended_action": "Use gentle moisturizers, avoid irritants, and consult a dermatologist.",
    },
    "melanoma": {
        "description": "Melanoma is a serious skin cancer that needs prompt medical attention.",
        "recommended_action": "Seek urgent dermatology review for diagnostic confirmation.",
    },
    "acne": {
        "description": "Acne commonly appears as pimples, blackheads, or inflamed lesions.",
        "recommended_action": "Use non-comedogenic products and consult a specialist if persistent.",
    },
    "psoriasis": {
        "description": "Psoriasis often appears as red, scaly patches due to autoimmune inflammation.",
        "recommended_action": "Arrange a dermatology visit for targeted treatment planning.",
    },
    "ringworm": {
        "description": "Ringworm is a fungal infection causing circular itchy rashes.",
        "recommended_action": "Keep affected area clean/dry and consider antifungal treatment advice.",
    },
    "vitiligo": {
        "description": "Vitiligo causes loss of skin pigmentation in patches.",
        "recommended_action": "Consult a dermatologist for long-term skin care and treatment options.",
    },
    "chickenpox": {
        "description": "Chickenpox typically causes itchy blisters with mild fever and fatigue.",
        "recommended_action": "Seek clinician guidance, isolate if contagious, and hydrate well.",
    },
}
